"use client";
import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import ProviderRoot from "./providers";
import { useEffect } from "react";
import { useRouter } from "next/router";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";

const dm_sans = DM_Sans({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }
// export const metadata: Metadata = {
//   title: "Bookklub",
//   description: "Bookklub app",
//   generator: "Next.js",
//   manifest: "/manifest.json",
//   keywords: ["nextjs", "nextjs13", "next13", "pwa", "next-pwa"],
//   themeColor: [{ media: "(prefers-color-scheme: dark)", color: "#fff" }],
//   authors: [{ name: "Parallax18" }],
//   viewport:
//     "minimum-scale=1, initial-scale=1, width=device-width, shrink-to-fit=no, viewport-fit=cover",
//   icons: [
//     { rel: "apple-touch-icon", url: "icons/book.png" },
//     { rel: "icon", url: "icons/book.png" },
//   ],
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const router = useRouter();

  // useEffect(() => {
  //   if (router.pathname === "/") {
  //     router.push("/login");
  //   }
  // }, [router]);
  const queryClient = new QueryClient();
  return (
    <QueryClientProvider client={queryClient}>
      <html lang="en">
        <body
          style={{
            backgroundImage: 'url("/Template.png")',
            width: "100%",
          }}
          className={dm_sans.className}
        >
          <ProviderRoot>{children}</ProviderRoot>
        </body>
      </html>
    </QueryClientProvider>
  );
}
