import { IBookItemCard } from "./components/home/BookItemCard";

export const dummyBooks: IBookItemCard[] = [
  {
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    state: "Classic",
    country: "USA",
    rating: "4.8",
    coverImg: "https://covers.openlibrary.org/b/id/8225266-L.jpg",
  },
  {
    title: "1984",
    author: "George Orwell",
    state: "Dystopian",
    country: "UK",
    rating: "4.7",
    coverImg: "https://covers.openlibrary.org/b/id/1532989-L.jpg",
  },
  {
    title: "Pride and Prejudice",
    author: "Jane Austen",
    state: "Classic",
    country: "UK",
    rating: "4.6",
    coverImg: "https://covers.openlibrary.org/b/id/8280206-L.jpg",
  },
  {
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    state: "Classic",
    country: "USA",
    rating: "4.4",
    coverImg: "https://covers.openlibrary.org/b/id/8299787-L.jpg",
  },
  {
    title: "Moby Dick",
    author: "Herman Melville",
    state: "Classic",
    country: "USA",
    rating: "4.3",
    coverImg: "https://covers.openlibrary.org/b/id/8221783-L.jpg",
  },
  {
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    state: "Classic",
    country: "USA",
    rating: "4.2",
    coverImg: "https://covers.openlibrary.org/b/id/8224814-L.jpg",
  },
  {
    title: "Brave New World",
    author: "Aldous Huxley",
    state: "Dystopian",
    country: "UK",
    rating: "4.1",
    coverImg: "https://covers.openlibrary.org/b/id/8220542-L.jpg",
  },
  {
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    state: "Fantasy",
    country: "UK",
    rating: "4.8",
    coverImg: "https://covers.openlibrary.org/b/id/8221054-L.jpg",
  },
  {
    title: "Harry Potter and the Sorcerer's Stone",
    author: "J.K. Rowling",
    state: "Fantasy",
    country: "UK",
    rating: "4.9",
    coverImg: "https://covers.openlibrary.org/b/id/7772516-L.jpg",
  },
  {
    title: "The Lord of the Rings",
    author: "J.R.R. Tolkien",
    state: "Fantasy",
    country: "UK",
    rating: "4.9",
    coverImg: "https://covers.openlibrary.org/b/id/7882651-L.jpg",
  },
];
