import { IBook, IBookItemCard } from "./components/home/BookItemCard";
import {
  IInboundRental,
  IOutboundRental,
} from "./components/Rentals/RentalItem";

export const dummyBooks: IBook[] = [
  {
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    genre: "Fiction",
    state: "Alabama",
    country: "USA",
    rating: "4.8",
    coverImg: "https://covers.openlibrary.org/b/id/8225266-L.jpg",
    ownerName: "John Doe",
    ownerPhone: "123-456-7890",
    ownerLocation: "New York, USA",
    description:
      "A gripping, heart-wrenching, and wholly remarkable tale of coming-of-age in a South poisoned by virulent prejudice.",
    rentInfo: "A must-read classic. Handle with care!",
  },
  {
    title: "1984",
    author: "George Orwell",
    genre: "Dystopian",
    state: "London",
    country: "UK",
    rating: "4.7",
    coverImg: "https://covers.openlibrary.org/b/id/1532989-L.jpg",
    ownerName: "Jane Smith",
    ownerPhone: "234-567-8901",
    ownerLocation: "London, UK",
    description:
      "A dystopian social science fiction novel and cautionary tale about the future.",
    rentInfo: "Highly recommended for readers interested in political fiction.",
  },
  {
    title: "Pride and Prejudice",
    author: "Jane Austen",
    genre: "Romance",
    state: "Hampshire",
    country: "UK",
    rating: "4.6",
    coverImg: "https://covers.openlibrary.org/b/id/8280206-L.jpg",
    ownerName: "Emily Brown",
    ownerPhone: "345-678-9012",
    ownerLocation: "Hampshire, UK",
    description:
      "A romantic novel that charts the emotional development of the protagonist Elizabeth Bennet.",
    rentInfo: "Perfect for lovers of classic romance.",
  },
  {
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    genre: "Fiction",
    state: "New York",
    country: "USA",
    rating: "4.4",
    coverImg: "https://covers.openlibrary.org/b/id/8299787-L.jpg",
    ownerName: "Michael Johnson",
    ownerPhone: "456-789-0123",
    ownerLocation: "New York, USA",
    description:
      "A story of the mysteriously wealthy Jay Gatsby and his love for the beautiful Daisy Buchanan.",
    rentInfo: "A timeless classic about the American dream.",
  },
  {
    title: "Moby Dick",
    author: "Herman Melville",
    genre: "Adventure",
    state: "Massachusetts",
    country: "USA",
    rating: "4.3",
    coverImg: "https://covers.openlibrary.org/b/id/8221783-L.jpg",
    ownerName: "Christopher Lee",
    ownerPhone: "567-890-1234",
    ownerLocation: "Massachusetts, USA",
    description: "An epic tale of the voyage of the whaling ship Pequod.",
    rentInfo: "Ideal for adventure lovers and maritime enthusiasts.",
  },
  {
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    genre: "Fiction",
    state: "California",
    country: "USA",
    rating: "4.2",
    coverImg: "https://covers.openlibrary.org/b/id/8224814-L.jpg",
    ownerName: "Nancy Williams",
    ownerPhone: "678-901-2345",
    ownerLocation: "California, USA",
    description:
      "A novel about the events in the life of a young man named Holden Caulfield.",
    rentInfo: "A powerful novel about teenage angst and rebellion.",
  },
  {
    title: "Brave New World",
    author: "Aldous Huxley",
    genre: "Dystopian",
    state: "Surrey",
    country: "UK",
    rating: "4.1",
    coverImg: "https://covers.openlibrary.org/b/id/8220542-L.jpg",
    ownerName: "Oliver Brown",
    ownerPhone: "789-012-3456",
    ownerLocation: "Surrey, UK",
    description:
      "A dystopian novel set in a futuristic World State of genetically modified citizens.",
    rentInfo: "A thought-provoking read about a dystopian future.",
  },
  {
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    genre: "Fantasy",
    state: "Birmingham",
    country: "UK",
    rating: "4.8",
    coverImg: "https://covers.openlibrary.org/b/id/8221054-L.jpg",
    ownerName: "Sophia Green",
    ownerPhone: "890-123-4567",
    ownerLocation: "Birmingham, UK",
    description: "A fantasy novel and children's book by J. R. R. Tolkien.",
    rentInfo: "A great adventure story for readers of all ages.",
  },
  {
    title: "Harry Potter and the Sorcerer's Stone",
    author: "J.K. Rowling",
    genre: "Fantasy",
    state: "Edinburgh",
    country: "UK",
    rating: "4.9",
    coverImg: "https://covers.openlibrary.org/b/id/7772516-L.jpg",
    ownerName: "William Black",
    ownerPhone: "901-234-5678",
    ownerLocation: "Edinburgh, UK",
    description:
      "The first book in the Harry Potter series, following Harry as he discovers his magical heritage.",
    rentInfo: "A must-read for all fantasy lovers.",
  },
  {
    title: "The Lord of the Rings",
    author: "J.R.R. Tolkien",
    genre: "Fantasy",
    state: "Oxfordshire",
    country: "UK",
    rating: "4.9",
    coverImg: "https://covers.openlibrary.org/b/id/7882651-L.jpg",
    ownerName: "Emma White",
    ownerPhone: "012-345-6789",
    ownerLocation: "Oxfordshire, UK",
    description:
      "An epic high-fantasy novel written by English author and scholar J. R. R. Tolkien.",
    rentInfo: "A monumental work of fantasy literature.",
  },
];

export const dummyRentals: (IOutboundRental | IInboundRental)[] = [
  // Outbound Rental
  {
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    rentDate: "2024-07-01",
    returnDate: "2024-07-15",
    status: "ACTIVE",
    coverImg: "https://covers.openlibrary.org/b/id/8299787-L.jpg",
    type: "OUTBOUND_RENTAL",
    rentees_phone: "123-456-7890",
    rentees_location: "Rentee Location",
    rentees_name: "Rentee Name",
  },

  // Outbound Rental
  {
    title: "1984",
    author: "George Orwell",
    rentDate: "2024-07-01",
    returnDate: "2024-07-15",
    status: "OVERDUE",
    coverImg: "https://covers.openlibrary.org/b/id/1532989-L.jpg",
    type: "OUTBOUND_RENTAL",
    rentees_phone: "234-567-8901",
    rentees_location: "Another Rentee Location",
    rentees_name: "Another Rentee Name",
  },

  // Outbound Rental
  {
    title: "Pride and Prejudice",
    author: "Jane Austen",
    rentDate: "2024-07-01",
    returnDate: "2024-07-15",
    status: "ACTIVE",
    coverImg: "https://covers.openlibrary.org/b/id/8280206-L.jpg",
    type: "OUTBOUND_RENTAL",
    rentees_phone: "345-678-9012",
    rentees_location: "Third Rentee Location",
    rentees_name: "Third Rentee Name",
  },

  // Inbound Rental
  {
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    rentDate: "2024-07-01",
    returnDate: "2024-07-15",
    status: "OVERDUE",
    coverImg: "https://covers.openlibrary.org/b/id/8225266-L.jpg",
    type: "INBOUND_RENTAL",
    owner_name: "Owner Name",
    owners_phone: "456-789-0123",
    owners_location: "Owner Location",
  },

  // Inbound Rental
  {
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    rentDate: "2024-07-01",
    returnDate: "2024-07-15",
    status: "ACTIVE",
    coverImg: "https://covers.openlibrary.org/b/id/8224814-L.jpg",
    type: "INBOUND_RENTAL",
    owner_name: "Another Owner",
    owners_phone: "567-890-1234",
    owners_location: "Another Owner Location",
  },

  // Inbound Rental
  {
    title: "Brave New World",
    author: "Aldous Huxley",
    rentDate: "2024-07-01",
    returnDate: "2024-07-15",
    status: "OVERDUE",
    coverImg: "https://covers.openlibrary.org/b/id/8220542-L.jpg",
    type: "INBOUND_RENTAL",
    owner_name: "Third Owner",
    owners_phone: "678-901-2345",
    owners_location: "Third Owner Location",
  },

  // Outbound Rental
  {
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    rentDate: "2024-07-01",
    returnDate: "2024-07-15",
    status: "ACTIVE",
    coverImg: "https://covers.openlibrary.org/b/id/8221054-L.jpg",
    type: "OUTBOUND_RENTAL",
    rentees_phone: "456-789-0123",
    rentees_location: "Rentee Location",
    rentees_name: "Rentee Name",
  },
];
